package lunes_23_10_23.ejercicio_clase_2.ejercicio2.domain;

import lunes_23_10_23.ejercicio_clase_2.ejercicio2.enums.OrderStatus;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;


public class Order {
    
    private Long id;
    private Client client;
    private LocalDate date;
    private Cart cart;
    private OrderStatus status;

    private static Long autoGeneratedId = 0l;

    public Order() {
    }

    public Order(Long id, Client client, LocalDate date, Cart cart){
        this.id = id;
        this.client = client;
        this.date = date;
        this.cart = cart;
        this.status = OrderStatus.PENDIENTE;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Client getClient() {
        return this.client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public LocalDate getDate() {
        return this.date;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }

    public Cart getCart() {
        return this.cart;
    }

    public void setCart(Cart cart) {
        this.cart = cart;
    }

    public OrderStatus getStatus() {
        return this.status;
    }

    public void setStatus(OrderStatus status) {
        this.status = status;
    }
    
    public static Long autoGenerateID(){
        return ++ autoGeneratedId;
    }

    public void payed(){
        this.setStatus(OrderStatus.PAGADO);
    }

    public void sent(){
        this.setStatus(OrderStatus.ENVIADO);
    }

    public void delivered(){
        this.setStatus(OrderStatus.ENTREGADO);
    }

    public Double purchaseAmount(){
        Double amount = 0d;
        for (Product prod : this.cart.getOrder().keySet()){
            amount += (prod.getPrecio() * this.cart.getOrder().get(prod));
        };
        return amount;
    }

    public void orderToString(){
        DateTimeFormatter fmt2 = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String client = this.getClient().getName();
        System.out.println("-".repeat(35));
        System.out.println("id " + this.getId() + " - " + this.date.format(fmt2) + " - Cliente: " + client);
        System.out.println("-".repeat(35));
        this.getCart().cartToString();
        System.out.println("-".repeat(35));
        System.out.println("Total de compra: " + this.purchaseAmount() + "\nEstado: " + this.getStatus());
        System.out.println("-".repeat(35));
    }
}
